name             "demoapache"
description      "Installs and configures all aspects of apache2 using Debian style symlinks with helper definitions"
maintainer       "Vincent"
license          "Apache 2.0"
version          "1.0.0"
